version: 0.0
os: linux
files:
  - source: /target/user-manager.war
    destination: /opt/tomcat/webapps
hooks:
  BeforeInstall:
    - location: aws_scripts/cleanup
      timeout: 300
      runas: root
